# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  EthaneEngine_config = debug
  Ethane_Editor_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  EthaneEngine_config = release
  Ethane_Editor_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  EthaneEngine_config = dist
  Ethane_Editor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad ImGui EthaneEngine Ethane-Editor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

EthaneEngine: GLFW Glad ImGui
ifneq (,$(EthaneEngine_config))
	@echo "==== Building EthaneEngine ($(EthaneEngine_config)) ===="
	@${MAKE} --no-print-directory -C EthaneEngine -f Makefile config=$(EthaneEngine_config)
endif

Ethane-Editor: EthaneEngine
ifneq (,$(Ethane_Editor_config))
	@echo "==== Building Ethane-Editor ($(Ethane_Editor_config)) ===="
	@${MAKE} --no-print-directory -C Ethane-Editor -f Makefile config=$(Ethane_Editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C EthaneEngine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C EthaneEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Ethane-Editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   EthaneEngine"
	@echo "   Ethane-Editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"